#داده بازیکنان
players = [
    {"id": 1, "name": "Pele", "position": "forward", "nationality": "Brazil"},
    {"id": 2, "name": "Diego Maradona", "position": "midfielder", "nationality": "Argentina"},
    {"id": 3, "name": "Zinedine Zidane", "position": "midfielder", "nationality": "France"},
    {"id": 4, "name": "Ronaldinho", "position": "forward", "nationality": "Brazil"},
    {"id": 5, "name": "Johan Cruyff", "position": "forward", "nationality": "Netherlands"},
    {"id": 6, "name": "Franz Beckenbauer", "position": "defender", "nationality": "Germany"},
    {"id": 7, "name": "Michel Platini", "position": "midfielder", "nationality": "France"},
    {"id": 8, "name": "Ronaldo Nazario", "position": "forward", "nationality": "Brazil"},
    {"id": 9, "name": "George Best", "position": "forward", "nationality": "Northern Ireland"},
    {"id": 10, "name": "Paolo Maldini", "position": "defender", "nationality": "Italy"},
    {"id": 11, "name": "Roberto Baggio", "position": "forward", "nationality": "Italy"},
    {"id": 12, "name": "David Beckham", "position": "midfielder", "nationality": "England"},
    {"id": 13, "name": "Garrincha", "position": "forward", "nationality": "Brazil"},
    {"id": 14, "name": "Alfredo Di Stefano", "position": "forward", "nationality": "Argentina"},
    {"id": 15, "name": "Xavi Hernandez", "position": "midfielder", "nationality": "Spain"},
    {"id": 16, "name": "Andres Iniesta", "position": "midfielder", "nationality": "Spain"},
    {"id": 17, "name": "Lionel Messi", "position": "forward", "nationality": "Argentina"},
    {"id": 18, "name": "Cristiano Ronaldo", "position": "forward", "nationality": "Portugal"},
    {"id": 19, "name": "Thierry Henry", "position": "forward", "nationality": "France"},
    {"id": 20, "name": "Iker Casillas", "position": "goalkeeper", "nationality": "Spain"},
    {"id": 21, "name": "Francesco Totti", "position": "forward", "nationality": "Italy"},
    {"id": 22, "name": "Roberto Carlos", "position": "defender", "nationality": "Brazil"},
    {"id": 23, "name": "Gianluigi Buffon", "position": "goalkeeper", "nationality": "Italy"},
    {"id": 24, "name": "Carlos Valderrama", "position": "midfielder", "nationality": "Colombia"},
    {"id": 25, "name": "Ryan Giggs", "position": "midfielder", "nationality": "Wales"},
    {"id": 26, "name": "Frank Lampard", "position": "midfielder", "nationality": "England"},
    {"id": 27, "name": "Steven Gerrard", "position": "midfielder", "nationality": "England"},
    {"id": 28, "name": "Patrick Vieira", "position": "midfielder", "nationality": "France"},
    {"id": 29, "name": "Kaka", "position": "midfielder", "nationality": "Brazil"},
    {"id": 30, "name": "Luis Figo", "position": "midfielder", "nationality": "Portugal"}
]
